### ISSUE TITLE
Graphite needs to be upgraded to 1.1.6

### ISSUE THREAD

**Issue by charmander** [Weasyl/weasyl#658]
It’s filling logs with garbage because of a bug fixed in 1.1.5 (we’re on 1.1.4).

**Comment by kfkitsune** [comment]
In theory this should be pulled in by the Ansible playbooks? See ``roles/graphite/tasks/main.yaml``

While I don't have much exposure to Docker, the way that the role reads, I _think_ the data would persist if the Docker image were re-pulled? And it looks like [graphiteapp/graphite-statsd](https://github.com/graphite-project/docker-graphite-statsd) was recently updated to 1.1.6-1.

If I am reading the docs for Ansible right, ``pull: yes`` should pull the [latest version of an image](https://docs.ansible.com/ansible/2.4/docker_container_module.html), so I guess this role just needs to be re-run?

```yaml
- name: Run graphite-statsd docker container named 'graphite'
  docker_container:
    name: graphite
    image: graphiteapp/graphite-statsd
    pull: yes
    state: started
    restart: yes
```
